<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.32.0.17</Version>
    <AssemblyName>AltMate</AssemblyName>
    <RootNamespace>AltMate</RootNamespace>
    <Description>Multi-character linking, housing, animation, and gil management for FFXIV.</Description>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="images\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NoireLib" Version="2.0.0.0" />
    <PackageReference Include="Penumbra.Api" Version="5.15.1" />
  </ItemGroup>
</Project>
